import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {openStore} from '../src/store.ts';
import {runSocialCycle,setAutonomy,autonomyStatus,validateAutonomousReply} from '../src/social-autonomy.ts';
const body='Queue retries need stable request identifiers and durable result records. How should a worker lease prevent duplicate execution?';
function fixture(){const dir=mkdtempSync(tmpdir()+'/autonomy-'),store=openStore(dir+'/data'),path=dir+'/identity.json';writeFileSync(path,JSON.stringify({name:'KestrelField',api_key:'test-secret'}));store.setOperator(true,'ollama','test-model',50);return {dir,store,path,close(){store.db.close();rmSync(dir,{recursive:true,force:true});}};}
function source(s:ReturnType<typeof openStore>,id:string,now:number){s.db.prepare('INSERT INTO social_discussions(id,title,body,author,community,seen_at,full_content,source_created_at) VALUES(?,?,?,?,?,?,1,?)').run(id,'Queue retries',body,'OtherAgent','agentops',now,new Date(now-1000).toISOString());}
const reply='Stable request identifiers should survive queue retries, with durable result records tied to each identifier. A worker lease can limit duplicate execution, but the receiver should also enforce idempotency when accepting a request. How does your queue reconcile a result after a timeout?';
test('autonomy defaults paused, publishes grounded fresh replies once and halts for verification',async()=>{const x=fixture(),now=Date.now();try{source(x.store,'one',now);let model=0,writes=0;const fake=async(url:any)=>{if(String(url).includes('/comments?'))return new Response(JSON.stringify({comments:[]}));if(url.endsWith('/agents/status'))return new Response(JSON.stringify({status:'claimed'}));if(url.endsWith('/comments')){writes++;return new Response(JSON.stringify({comment:{id:'comment-one',verification_status:'pending',verification:{verification_code:'secret',challenge_text:'challenge',expires_at:new Date(now+7200000).toISOString()}}}));}return new Response(JSON.stringify({post:{id:'one',title:'Queue retries',content:body,author:{name:'OtherAgent'}}}));};const gen=async()=>{model++;return {text:decision(reply),provider:'ollama',model:'test'};};assert.deepEqual(await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen),{skipped:true});setAutonomy(x.store,true);const observed=await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen);assert.equal(observed.status,'PENDING_VERIFICATION',JSON.stringify(observed));source(x.store,'two',now+3600001);await runSocialCycle(x.store,x.path,fake as typeof fetch,now+3600001,gen);assert.equal(model,1);assert.equal(writes,1);assert.equal(autonomyStatus(x.store).blocked,'PENDING_VERIFICATION');}finally{x.close();}});
test('pause during generation retains draft; stale or changed sources never publish',async()=>{const x=fixture(),now=Date.now();try{source(x.store,'one',now);setAutonomy(x.store,true);let writes=0;const fake=async(url:any)=>{if(String(url).includes('/comments?'))return new Response(JSON.stringify({comments:[]}));if(url.endsWith('/comments'))writes++;return new Response(JSON.stringify({post:{id:'one',title:'Queue retries',content:body,author:{name:'OtherAgent'}}}));};const gen=async()=>{setAutonomy(x.store,false);return {text:decision(reply),provider:'ollama',model:'test'};};const observed=await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen);assert.equal(observed.status,'DRAFT',JSON.stringify(observed));assert.equal(writes,0);assert.equal(x.store.db.prepare('SELECT status FROM social_replies').get()?.status,'DRAFT');source(x.store,'two',now+3600001);setAutonomy(x.store,true);assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now+3600001,gen)).error_code,'source_changed');assert.equal(writes,0);}finally{x.close();}});
test('reply guard rejects promotion, credential requests and unrelated model output',()=>{assert.equal(validateAutonomousReply(reply,body),reply);assert.throws(()=>validateAutonomousReply(reply+' https://example.com',body));assert.throws(()=>validateAutonomousReply(reply+' Send us your API key.',body));assert.throws(()=>validateAutonomousReply('This unrelated response talks about gardening and vegetables and sunshine rather than the technical discussion.',body));});
test('failed model calls consume persistent daily budget and do not leak exception messages',async()=>{const x=fixture(),now=Date.now();try{setAutonomy(x.store,true);let calls=0;const fake=async(url:any)=>{if(String(url).includes('/comments?'))return new Response(JSON.stringify({comments:[]}));const id=String(url).split('/').pop();return new Response(JSON.stringify({post:{id,title:'Queue retries',content:body,author:{name:'OtherAgent'}}}));};const gen=async()=>{calls++;throw Error('secret provider details');};for(let i=0;i<7;i++){source(x.store,'budget-'+i,now+i*3600001);const result=await runSocialCycle(x.store,x.path,fake as typeof fetch,now+i*3600001,gen);if(i<6)assert.equal(result.error_code,'social_cycle_failed');else assert.equal(result.skipped,true);}assert.equal(calls,6);assert.equal(autonomyStatus(x.store,now+7*3600001).generation_attempts,6);}finally{x.close();}});
test('status separates rolling write, generation, solver and visibility counts and reports the binding limit',()=>{const x=fixture(),now=Date.now();try{setAutonomy(x.store,true);source(x.store,'status-post',now);for(let i=0;i<4;i++){source(x.store,'status-write-'+i,now);x.store.db.prepare("INSERT INTO social_replies(id,post_id,body,status,attempted_at) VALUES(?,?,?,'VERIFICATION_FAILED',?)").run('status-'+i,'status-write-'+i,'Reply '+i,now-1000+i);}x.store.db.prepare("INSERT INTO social_visibility(reply_id,visibility,checked_at,verification_status) VALUES('status-0','VISIBLE',?,'failed')").run(now);x.store.db.prepare("INSERT INTO social_generation(id,post_id,started_at,status) VALUES('gen-status','status-post',?,'FAILED')").run(now-1000);x.store.db.prepare("INSERT INTO social_verification_attempts(target,started_at,status) VALUES('reply:status-0',?,'FAILED')").run(now-1000);const status=autonomyStatus(x.store,now);assert.equal(status.reply_attempts,4);assert.equal(status.generation_attempts,1);assert.equal(status.verification_attempts,1);assert.equal(status.visible_replies,1);assert.equal(status.verified_replies,0);assert.equal(status.waiting_reason,'reply_daily_limit');assert.equal(status.next_eligible_at,now-1000+86400000);const later=autonomyStatus(x.store,now+86400000);assert.equal(later.reply_attempts,0);assert.equal(later.waiting_reason,null);setAutonomy(x.store,false);assert.equal(autonomyStatus(x.store,now).next_eligible_at,null);}finally{x.close();}});
test('reply rejection codes identify the failed quality rule',()=>{assert.throws(()=>validateAutonomousReply('short',body),/reply_too_short/);assert.throws(()=>validateAutonomousReply(reply+' Why? Another question?',body),/reply_too_many_questions/);assert.throws(()=>validateAutonomousReply(reply+' https://example.com',body),/reply_promotion_or_link/);assert.throws(()=>validateAutonomousReply(reply+' Send us your API key.',body),/reply_credential_or_solicitation/);assert.throws(()=>validateAutonomousReply('x'.repeat(1201),body),/reply_too_long/);});

function decision(replyText:string){return JSON.stringify({action:"help",need:"Understand reliable queue retries and durable results.",evidence:body.slice(0,80),reason:"Offer a concrete mechanism addressing the source constraint.",body:replyText});}
