import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {openStore} from '../src/store.ts';
import {runSocialCycle,setAutonomy,autonomyStatus,validateAutonomousReply} from '../src/social-autonomy.ts';
const body='Queue retries need stable request identifiers and durable result records. How should a worker lease prevent duplicate execution?';
function fixture(){const dir=mkdtempSync(tmpdir()+'/autonomy-'),store=openStore(dir+'/data'),path=dir+'/identity.json';writeFileSync(path,JSON.stringify({name:'KestrelField',api_key:'test-secret'}));store.setOperator(true,'ollama','test-model',50);return {dir,store,path,close(){store.db.close();rmSync(dir,{recursive:true,force:true});}};}
function source(s:ReturnType<typeof openStore>,id:string,now:number){s.db.prepare('INSERT INTO social_discussions(id,title,body,author,community,seen_at,full_content,source_created_at) VALUES(?,?,?,?,?,?,1,?)').run(id,'Queue retries',body,'OtherAgent','agentops',now,new Date(now-1000).toISOString());}
const reply='Stable request identifiers should survive queue retries, with durable result records tied to each identifier. A worker lease can limit duplicate execution, but the receiver should also enforce idempotency when accepting a request. How does your queue reconcile a result after a timeout?';
test('autonomy defaults paused, publishes grounded fresh replies once and halts for verification',async()=>{const x=fixture(),now=Date.now();try{source(x.store,'one',now);let model=0,writes=0;const fake=async(url:any)=>{if(url.endsWith('/agents/status'))return new Response(JSON.stringify({status:'claimed'}));if(url.endsWith('/comments')){writes++;return new Response(JSON.stringify({comment:{id:'comment-one',verification_status:'pending',verification:{verification_code:'secret',challenge_text:'challenge',expires_at:new Date(now+7200000).toISOString()}}}));}return new Response(JSON.stringify({post:{id:'one',title:'Queue retries',content:body,author:{name:'OtherAgent'}}}));};const gen=async()=>{model++;return {text:reply,provider:'ollama',model:'test'};};assert.deepEqual(await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen),{skipped:true});setAutonomy(x.store,true);assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen)).status,'PENDING_VERIFICATION');source(x.store,'two',now+3600001);await runSocialCycle(x.store,x.path,fake as typeof fetch,now+3600001,gen);assert.equal(model,1);assert.equal(writes,1);assert.equal(autonomyStatus(x.store).blocked,'PENDING_VERIFICATION');}finally{x.close();}});
test('pause during generation retains draft; stale or changed sources never publish',async()=>{const x=fixture(),now=Date.now();try{source(x.store,'one',now);setAutonomy(x.store,true);let writes=0;const fake=async(url:any)=>{if(url.endsWith('/comments'))writes++;return new Response(JSON.stringify({post:{id:'one',title:'Queue retries',content:body,author:{name:'OtherAgent'}}}));};const gen=async()=>{setAutonomy(x.store,false);return {text:reply,provider:'ollama',model:'test'};};assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen)).status,'DRAFT');assert.equal(writes,0);assert.equal(x.store.db.prepare('SELECT status FROM social_replies').get()?.status,'DRAFT');source(x.store,'two',now+3600001);setAutonomy(x.store,true);assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now+3600001,gen)).error_code,'source_changed');assert.equal(writes,0);}finally{x.close();}});
test('reply guard rejects promotion, credential requests and unrelated model output',()=>{assert.equal(validateAutonomousReply(reply,body),reply);assert.throws(()=>validateAutonomousReply(reply+' https://example.com',body));assert.throws(()=>validateAutonomousReply(reply+' Send us your API key.',body));assert.throws(()=>validateAutonomousReply('This unrelated response talks about gardening and vegetables and sunshine rather than the technical discussion.',body));});
test('failed model calls consume persistent daily budget and do not leak exception messages',async()=>{const x=fixture(),now=Date.now();try{setAutonomy(x.store,true);let calls=0;const fake=async(url:any)=>{const id=String(url).split('/').pop();return new Response(JSON.stringify({post:{id,title:'Queue retries',content:body,author:{name:'OtherAgent'}}}));};const gen=async()=>{calls++;throw Error('secret provider details');};for(let i=0;i<4;i++){source(x.store,'budget-'+i,now+i*3600001);const result=await runSocialCycle(x.store,x.path,fake as typeof fetch,now+i*3600001,gen);if(i<3)assert.equal(result.error_code,'social_cycle_failed');else assert.equal(result.skipped,true);}assert.equal(calls,3);assert.equal(autonomyStatus(x.store,now+4*3600001).generation_attempts,3);}finally{x.close();}});
