import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {openStore} from '../src/store.ts';
import {discoverDiscussions} from '../src/social-discovery.ts';
function fixture(){const dir=mkdtempSync(tmpdir()+'/discovery-'),store=openStore(dir+'/data'),path=dir+'/identity.json';writeFileSync(path,JSON.stringify({name:'KestrelField',api_key:'test-secret'}));return {store,path,close(){store.db.close();rmSync(dir,{recursive:true,force:true});}};}
const json=(data:unknown)=>new Response(JSON.stringify(data));
const candidate=(id:string,now:number)=>({id,type:'post',title:'Reliable agent tasks',content:'Agent queue retries and durable results.',author:{name:'Agent-'+id},created_at:new Date(now-1000).toISOString()});
function metrics(x:ReturnType<typeof fixture>){return JSON.parse(String(x.store.db.prepare('SELECT snapshot FROM social_scan WHERE id=1').get()?.snapshot));}
test('discovery uses healthy sources after a search failure and preserves exact diagnostic counts',async()=>{const x=fixture(),now=Date.now();try{let searches=0,details=0;const fake=async(url:any)=>{const u=new URL(url);if(u.pathname.endsWith('/search')){searches++;if(searches===1)throw Error('private upstream details');return json({results:[candidate('good',now)]});}if(u.pathname.endsWith('/posts'))return json({posts:[candidate('good',now),candidate('own',now),{...candidate('old',now),created_at:new Date(now-8*86400000).toISOString()},{...candidate('other',now),title:'Garden vegetables',content:'Growing carrots outdoors'}, {id:'bad'}].map(p=>p.id==='own'?{...p,author:{name:'KestrelField'}}:p)});details++;return json({post:candidate('good',now)});};assert.deepEqual(await discoverDiscussions(x.store,x.path,fake as typeof fetch,now),{found:1,detail_failures:0});assert.equal(details,1);const m=metrics(x);assert.equal(m.sources.length,4);assert.equal(m.sources[0].error_code,'source_connection_or_response_error');assert.equal(m.fetched,11);assert.equal(m.accepted,1);assert.equal(m.rejections.own_post,1);assert.equal(m.rejections.outside_freshness_window,1);assert.equal(m.rejections.unrelated_topic,1);assert.equal(m.rejections.malformed_candidate,2);assert.ok(m.rejections.duplicate_candidate>=4);assert.ok(!JSON.stringify(m).includes('private upstream'));assert.equal(x.store.db.prepare('SELECT error_code FROM social_scan').get()?.error_code,'discovery_partial_failure');assert.deepEqual(await discoverDiscussions(x.store,x.path,fake as typeof fetch,now+1),{skipped:true});assert.equal(metrics(x).accepted,1);}finally{x.close();}});
test('known replied posts cannot consume the detail budget; feed reads allow bounded larger payloads',async()=>{const x=fixture(),now=Date.now();try{const old=candidate('handled',now);x.store.db.prepare('INSERT INTO social_discussions(id,title,body,author,community,seen_at,full_content,source_created_at) VALUES(?,?,?,?,?,?,1,?)').run(old.id,old.title,old.content,old.author.name,'agents',now,old.created_at);x.store.db.prepare("INSERT INTO social_replies(id,post_id,body,status) VALUES('reply','handled','Existing reply','PUBLISHED')").run();let details=0;const fake=async(url:any)=>{const u=new URL(url);if(u.pathname.endsWith('/search'))return json({results:[old]});if(u.pathname.endsWith('/posts'))return json({posts:[old,{...candidate('new',now),content:'Agent workflows '+ 'x'.repeat(80000)}]});details++;assert.ok(u.pathname.endsWith('/new'));return json({post:candidate('new',now)});};assert.equal((await discoverDiscussions(x.store,x.path,fake as typeof fetch,now)).found,1);assert.equal(details,1);assert.equal(metrics(x).rejections.already_handled,1);assert.ok(metrics(x).sources.every((s:any)=>!s.error_code));}finally{x.close();}});
test('all failed sources and malformed detail dates remain visible and never produce eligible posts',async()=>{const x=fixture(),now=Date.now();try{const fail=async()=>new Response('{}',{status:429});await discoverDiscussions(x.store,x.path,fail as typeof fetch,now);assert.equal(x.store.db.prepare('SELECT error_code FROM social_scan').get()?.error_code,'all_discovery_sources_failed');assert.ok(metrics(x).sources.every((s:any)=>s.error_code==='moltbook_http_429'));const fake=async(url:any)=>{const u=new URL(url);if(u.pathname.endsWith('/search'))return json({results:[candidate('bad-date',now)]});if(u.pathname.endsWith('/posts'))return json({posts:[]});return json({post:{...candidate('bad-date',now),created_at:'invalid'}});};assert.equal((await discoverDiscussions(x.store,x.path,fake as typeof fetch,now+1800001)).found,0);assert.equal(metrics(x).rejections.missing_post_date,1);assert.equal(x.store.db.prepare('SELECT count(*) AS n FROM social_discussions').get()?.n,0);}finally{x.close();}});
test('recent feed text posts are accepted, comment results rejected, and full detail replaces snippets',async()=>{const x=fixture(),now=Date.now();try{let reads=0;const fake=async(url:any)=>{const u=new URL(url);if(u.pathname.endsWith('/search'))return json({results:[{...candidate('comment',now),type:'comment'}]});if(u.pathname.endsWith('/posts'))return json({posts:[{...candidate('recent-text',now),type:'text',content:'Agent tools snippet'}]});reads++;return json({post:{...candidate('recent-text',now),type:'text',content:'Full agent tools discussion about durable queue results and reliable retries.'}});};assert.equal((await discoverDiscussions(x.store,x.path,fake as typeof fetch,now)).found,1);assert.equal(reads,1);assert.equal(metrics(x).rejections.malformed_candidate,2);assert.match(String(x.store.db.prepare('SELECT body FROM social_discussions').get()?.body),/^Full agent tools/);}finally{x.close();}});
