import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { openStore } from '../src/store.ts';

function fixture(fn:(s:ReturnType<typeof openStore>)=>void){const dir=mkdtempSync(tmpdir()+'/exchange-');const s=openStore(dir);try{fn(s);}finally{s.db.close();rmSync(dir,{recursive:true,force:true});}}
test('registration stores hashed credentials and grants test credits',()=>fixture(s=>{const a=s.register('buyer','test');const row=s.db.prepare('SELECT * FROM agents WHERE id=?').get(a.id);assert.equal(row?.credits,100);assert.notEqual(row?.token_hash,a.api_key);assert.throws(()=>s.register('buyer','duplicate'));}));
test('duplicate submissions reserve credits only once and reject changed input',()=>fixture(s=>{const a=s.register('buyer','test');const first=s.submit(a.id,'text-stats','{"text":"hello"}','request-1');const second=s.submit(a.id,'text-stats','{"text":"hello"}','request-1');assert.equal(first?.id,second?.id);assert.equal(s.db.prepare('SELECT credits FROM agents WHERE id=?').get(a.id)?.credits,99);assert.throws(()=>s.submit(a.id,'sha256','{"text":"hello"}','request-1'));}));
test('built-in jobs complete and invalid JSON refunds exactly once',()=>fixture(s=>{const a=s.register('buyer','test');const good=s.submit(a.id,'text-stats','{"text":"hello world"}','request-1');const bad=s.submit(a.id,'json-format','{"text":"bad json"}','request-2');s.tick();assert.equal(s.db.prepare('SELECT status FROM jobs WHERE id=?').get(good?.id)?.status,'COMPLETED');assert.equal(s.db.prepare('SELECT status FROM jobs WHERE id=?').get(bad?.id)?.status,'FAILED');assert.equal(s.db.prepare('SELECT credits FROM agents WHERE id=?').get(a.id)?.credits,99);s.tick();assert.equal(s.db.prepare('SELECT credits FROM agents WHERE id=?').get(a.id)?.credits,99);}));
test('provider permissions and marketplace fee settle atomically',()=>fixture(s=>{const buyer=s.register('buyer','test'),provider=s.register('provider','test'),other=s.register('other','test');s.db.prepare('INSERT INTO services(id,provider_id,name,description,category,price) VALUES(?,?,?,?,?,?)').run('custom',provider.id,'Custom','Custom service','Text',20);const job=s.submit(buyer.id,'custom','{"text":"input"}','request-1');assert.throws(()=>s.settle(String(job?.id),'COMPLETED','{}',other.id));assert.equal(s.db.prepare('SELECT status FROM jobs WHERE id=?').get(job?.id)?.status,'QUEUED');s.settle(String(job?.id),'COMPLETED','{"text":"output"}',provider.id);assert.equal(s.db.prepare('SELECT credits FROM agents WHERE id=?').get(buyer.id)?.credits,80);assert.equal(s.db.prepare('SELECT credits FROM agents WHERE id=?').get(provider.id)?.credits,118);assert.equal(s.db.prepare("SELECT amount FROM ledger WHERE kind='platform_test_revenue'").get()?.amount,2);assert.throws(()=>s.settle(String(job?.id),'COMPLETED','{}',provider.id));}));
test('cancellation and insufficient funds leave a consistent ledger',()=>fixture(s=>{const buyer=s.register('buyer','test'),provider=s.register('provider','test');s.db.prepare('INSERT INTO services(id,provider_id,name,description,category,price) VALUES(?,?,?,?,?,?)').run('custom',provider.id,'Custom','Custom service','Text',101);assert.throws(()=>s.submit(buyer.id,'custom','{}','request-1'));assert.equal(s.db.prepare('SELECT count(*) AS n FROM jobs').get()?.n,0);const job=s.submit(buyer.id,'sha256','{"text":"input"}','request-2');assert.throws(()=>s.settle(String(job?.id),'CANCELLED','{}',provider.id));s.settle(String(job?.id),'CANCELLED','{}',buyer.id);assert.equal(s.db.prepare('SELECT credits FROM agents WHERE id=?').get(buyer.id)?.credits,100);s.tick();assert.equal(s.db.prepare('SELECT status FROM jobs WHERE id=?').get(job?.id)?.status,'CANCELLED');}));
