import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {openStore} from '../src/store.ts';
import {classifyDiscussion,chooseDiscussion,planningSnapshot} from '../src/planning.ts';
import {retrieveMemory,learnFromOutcomes} from '../src/memory.ts';
import {runSocialCycle,setAutonomy} from '../src/social-autonomy.ts';
import {recordPrivateIncidents,conversationContext,parseSocialDecision,invitationEligible} from '../src/social-judgment.ts';
import {runAdminChat,queueChat} from '../src/admin-chat.ts';
import {runAgentCore,eligibleProjects} from '../src/agent-core.ts';
const source='I am a new agent working with Python and text tools. My human challenge is to document the journey of an agent earning real income honestly.';
const contribution='For your Python and text tools journey, start with a small summarization service and document its input, expected output and delivery time. Testing that service with another agent can reveal whether the result is useful before you pursue income. A free trial provides usage evidence, but cannot establish willingness to pay.';
function fixture(){const dir=mkdtempSync(tmpdir()+'/judgment-'),store=openStore(dir+'/data'),path=dir+'/identity.json';writeFileSync(path,JSON.stringify({name:'KestrelField',api_key:'secret'}));store.setOperator(true,'ollama','test',50);setAutonomy(store,true);return {dir,store,path,close(){store.db.close();rmSync(dir,{recursive:true,force:true});}};}
function post(s:any,id:string,body:string,now:number,author='hermesdejoel'){s.db.prepare('INSERT INTO social_discussions(id,title,body,author,community,seen_at,full_content,source_created_at) VALUES(?,?,?,?,?,?,1,?)').run(id,'Agent introduction',body,author,'agents',now,new Date(now-1000).toISOString());}
const decision=(action='invite',body=contribution)=>JSON.stringify({action,body,need:'Explore honest earning through useful agent services.',evidence:source.slice(0,80),reason:'A small text-service trial could establish usefulness without promising revenue.'});
test('prospective provider is recognised without falsely labelling them as a buyer',()=>{const x=fixture(),now=Date.now();try{post(x.store,'opportunity',source,now);post(x.store,'essay','Agent queue retries and verification need robust tracking.',now,'other');const c=classifyDiscussion(source);assert.equal(c.opportunity,true);assert.equal(c.demand,false);assert.equal(chooseDiscussion(x.store,now)?.p.id,'opportunity');assert.equal(chooseDiscussion(x.store,now)?.goal,'tester_opportunity');assert.equal(classifyDiscussion('Imagine my agent earning income.').opportunity,false);}finally{x.close();}});
test('bounded thread research precedes an invitation, records evidence and permits only one per day',async()=>{const x=fixture(),now=Date.now();try{post(x.store,'post',source,now);let reads=0,writes=0,calls=0;const fake:any=async(url:string,init:any)=>{if(url.includes('/comments?')){reads++;return new Response(JSON.stringify({comments:[{id:'comment',author:{name:'other'},content:'Have you tested whether another agent finds that service useful?'}]}));}if(url.endsWith('/agents/status'))return new Response(JSON.stringify({status:'claimed'}));if(url.endsWith('/comments')){writes++;const body=JSON.parse(init.body).content;assert.match(body,/100 test credits, not cash/);assert.match(body,/I operate Literate Bassoon/);return new Response(JSON.stringify({comment:{id:'published'}}));}return new Response(JSON.stringify({post:{id:'post',title:'Agent introduction',content:source,author:{name:'hermesdejoel'}}}));};const gen:any=async(_cfg:any,task:string,input:string)=>{calls++;assert.equal(task,'social-decision');assert.ok(reads>0);const context=JSON.parse(input);assert.equal(context.thread.length,1);assert.equal(context.opportunity.eligible,true);assert.ok(context.opportunity.services.length);return {text:decision()};};const r=await runSocialCycle(x.store,x.path,fake,now,gen);assert.equal(r.status,'PUBLISHED',JSON.stringify(r));assert.equal(calls,1);assert.equal(writes,1);assert.equal(planningSnapshot(x.store).decisions[0].action,'invite');assert.equal(invitationEligible(x.store,source,'another',now+1),false);assert.equal(invitationEligible(x.store,source,'hermesdejoel',now+86400001),false);assert.equal(invitationEligible(x.store,source,'another',now+86400001),true);}finally{x.close();}});
test('abstention consumes a generation reservation but performs no write and is not regenerated',async()=>{const x=fixture(),now=Date.now();try{post(x.store,'post',source,now);let calls=0,writes=0;const fake:any=async(url:string)=>{if(url.includes('/comments?'))return new Response(JSON.stringify({comments:[]}));if(url.endsWith('/comments'))writes++;return new Response(JSON.stringify({post:{id:'post',title:'Agent introduction',content:source,author:{name:'hermesdejoel'}}}));};const gen:any=async()=>{calls++;return {text:decision('abstain','')};};assert.equal((await runSocialCycle(x.store,x.path,fake,now,gen)).status,'ABSTAINED');await runSocialCycle(x.store,x.path,fake,now+3600001,gen);assert.equal(calls,1);assert.equal(writes,0);assert.equal(x.store.db.prepare('SELECT status FROM kestrel_plans').get()?.status,'ABSTAINED');}finally{x.close();}});
test('failed research and invented evidence cannot produce a public write',async()=>{const x=fixture(),now=Date.now();try{post(x.store,'post',source,now);let calls=0;const fake:any=async(url:string)=>url.includes('/comments?')?new Response('unavailable',{status:503}):new Response(JSON.stringify({post:{id:'post',title:'Agent introduction',content:source,author:{name:'hermesdejoel'}}}));await runSocialCycle(x.store,x.path,fake,now,async()=>{calls++;return {text:decision(),provider:'ollama',model:'test'};});assert.equal(calls,0);assert.equal(x.store.db.prepare('SELECT count(*) AS n FROM social_replies').get()?.n,0);assert.throws(()=>parseSocialDecision(decision(), 'Unrelated source',true),/decision_invalid_evidence/);assert.throws(()=>parseSocialDecision(decision(),source,false),/decision_invitation_not_eligible/);}finally{x.close();}});
test('verification incidents are private and irrelevant verification lessons are excluded from earning discussions',()=>{const x=fixture(),now=Date.now();try{post(x.store,'post',source,now);x.store.db.prepare("INSERT INTO social_replies(id,post_id,body,status) VALUES('manual','post','Admin selected this reply','VERIFICATION_FAILED')").run();learnFromOutcomes(x.store,now);recordPrivateIncidents(x.store,now);recordPrivateIncidents(x.store,now+1);assert.equal(planningSnapshot(x.store).incidents.length,1);assert.ok(!retrieveMemory(x.store,'future',source,now).includes('verification'));assert.ok(!retrieveMemory(x.store,'general','Independent verification and delivery receipts',now).includes('Treat visibility and verification independently'));assert.match(retrieveMemory(x.store,'ops','Moltbook verification failure and delivery visibility',now),/Treat visibility and verification independently/);assert.equal(conversationContext(x.store,'hermesdejoel')[0].origin,'ADMIN_INITIATED');}finally{x.close();}});
test('admin chat receives actual relevant conversations and preserves manual attribution',async()=>{const x=fixture(),now=Date.now();try{post(x.store,'post',source,now);x.store.db.prepare("INSERT INTO social_replies(id,post_id,body,status) VALUES('manual','post','Admin selected this reply','PUBLISHED')").run();queueChat(x.store,'Recall your conversation with hermesdejoel','recall-hermes',now);await runAdminChat(x.store,async(_cfg,task,input)=>{assert.equal(task,'admin-chat');const context=JSON.parse(input);assert.equal(context.conversations[0].author,'hermesdejoel');assert.equal(context.conversations[0].origin,'ADMIN_INITIATED');assert.match(context.conversations[0].source_excerpt,/earning real income/);return {text:'Admin initiated that contribution.',provider:'ollama',model:'test'};},now+1);assert.equal(x.store.db.prepare('SELECT status FROM kestrel_chat').get()?.status,'ANSWERED');}finally{x.close();}});
test('unchanged inspections cannot monopolise the core, including legacy evidence',async()=>{const x=fixture(),now=Date.now();try{const make=(project_id:string,tools:string[])=>({project_id,tools,reason:'Investigate only observed evidence without asserting causation.',next_step:'Record a proposed next step, not an implemented change.'});await runAgentCore(x.store,async()=>({text:JSON.stringify(make('exchange_health',['inspect_health','inspect_jobs'])),provider:'ollama',model:'test'}),now);assert.ok(!eligibleProjects(x.store,now).some(p=>p.id==='exchange_health'));x.store.db.prepare('UPDATE kestrel_tasks SET inspection_fingerprint=NULL').run();assert.ok(!eligibleProjects(x.store,now).some(p=>p.id==='exchange_health'));await runAgentCore(x.store,async(_cfg,_task,input)=>{assert.ok(!JSON.parse(input).eligible_project_ids.includes('exchange_health'));return {text:JSON.stringify(make('agent_onboarding',['inspect_onboarding'])),provider:'ollama',model:'test'};},now+3600001);assert.ok(!eligibleProjects(x.store,now+3600001).some(p=>p.id==='agent_onboarding'));x.store.register('new-customer','A fresh registration');assert.ok(eligibleProjects(x.store,now+3600002).some(p=>p.id==='agent_onboarding'));}finally{x.close();}});
