import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {openStore} from '../src/store.ts';
import {recordObservation,moderationPolicy,reconcileProfileAndPosts,assertModerationAllowsWrite} from '../src/social-observations.ts';
import {publishReply,reviewReply,draftReply,syncSocialProfile,expectedProfileDescription} from '../src/social.ts';
import {parseSocialDecision,sourceExcerpts} from '../src/social-judgment.ts';
import {validateContributionHistory,similarContribution} from '../src/social-quality.ts';
import {learnFromOutcomes,retrieveMemory} from '../src/memory.ts';
import {scanFollowups} from '../src/social-threads.ts';
import {setAutonomy,runSocialCycle,autonomyStatus} from '../src/social-autonomy.ts';
function fixture(){const dir=mkdtempSync(tmpdir()+'/moderation-'),store=openStore(dir+'/data'),path=dir+'/identity.json',now=Date.now();writeFileSync(path,JSON.stringify({name:'KestrelField',api_key:'test-secret'}));store.setOperator(true,'ollama','test',50);setAutonomy(store,true);store.db.prepare("INSERT INTO social_discussions(id,title,body,author,community,seen_at,full_content,source_created_at) VALUES('p','Reliable state','Independent observers need an append-only state log.','Alice','agents',?,1,?)").run(now,new Date(now-1000).toISOString());return {store,path,dir,now,close(){store.db.close();rmSync(dir,{recursive:true,force:true});}};}
function reply(x:any,id='r',body='A specific authored reply'){x.store.db.prepare("INSERT INTO social_replies(id,post_id,parent_id,body,status,comment_id,attempted_at) VALUES(?,'p',?,?,'PUBLISHED',?,?)").run(id,id==='r'?null:'parent-'+id,body,'comment-'+id,x.now-7200000);}
test('spam, verification and each visibility surface persist independently; omission never clears known spam',()=>{const x=fixture();try{reply(x);recordObservation(x.store,'reply:r','profile_api',{is_spam:true,verification_status:'verified'},true,x.now);recordObservation(x.store,'reply:r','public_thread_api',undefined,false,x.now+1);recordObservation(x.store,'reply:r','profile_api',{verification_status:'verified'},true,x.now+2);recordObservation(x.store,'reply:r','profile_api',{verification_status:'verified'},true,x.now+3);assert.equal(x.store.db.prepare("SELECT status FROM social_replies").get()?.status,'PUBLISHED');assert.equal(x.store.db.prepare("SELECT moderation FROM social_observations WHERE surface='profile_api'").get()?.moderation,'UNKNOWN');assert.equal(moderationPolicy(x.store,x.now+3).restricted_items,1);assert.equal(x.store.db.prepare('SELECT count(*) AS n FROM social_observation_history').get()?.n,3);assert.equal(x.store.db.prepare('SELECT count(*) AS n FROM kestrel_incidents').get()?.n,1);learnFromOutcomes(x.store,x.now+4);assert.equal(x.store.db.prepare("SELECT evidence_count FROM kestrel_lessons WHERE kind='moltbook_spam_observed'").get()?.evidence_count,1);assert.ok(!retrieveMemory(x.store,'future','Specific authored reply state logs',x.now+4).includes('Earlier published reply (untrusted'));}finally{x.close();}});
test('spam cooldowns resume without human approval and repeated reads do not extend them',async()=>{const x=fixture();try{recordObservation(x.store,'reply:a','owner_thread_api',{is_spam:true},true,x.now);assert.equal(moderationPolicy(x.store,x.now).cooldown_until,x.now+6*3600000);recordObservation(x.store,'reply:a','owner_thread_api',{is_spam:true},true,x.now+3600000);assert.equal(moderationPolicy(x.store,x.now+3600000).cooldown_until,x.now+6*3600000);assert.equal(moderationPolicy(x.store,x.now+6*3600000).cooldown_until,null);recordObservation(x.store,'reply:b','owner_thread_api',{is_spam:true},true,x.now+3600000);assert.equal(autonomyStatus(x.store,x.now+3600000).waiting_reason,'moderation_cooldown');assert.equal(moderationPolicy(x.store,x.now+3600000).cooldown_until,x.now+25*3600000);assert.equal(moderationPolicy(x.store,x.now+24*3600000).cooldown_until,x.now+25*3600000);assert.equal(moderationPolicy(x.store,x.now+25*3600000).cooldown_until,null);assert.equal(moderationPolicy(x.store,x.now+25*3600000).promotion_allowed,false);assert.equal(moderationPolicy(x.store,x.now+8*86400000).promotion_allowed,true);}finally{x.close();}});
test('confirmed restrictions block manual and autonomous writes while reads continue',async()=>{const x=fixture();try{const d=draftReply(x.store,'p');reviewReply(x.store,d.id,'A manually authored useful suggestion.','APPROVED');recordObservation(x.store,'post:intro','post_api',{is_spam:true},true,x.now);let writes=0,models=0;const fake:any=async(url:string,init:any)=>{if(init.method==='POST')writes++;if(url.endsWith('/agents/status'))return Response.json({status:'claimed'});if(url.includes('/comments?'))return Response.json({comments:[]});return Response.json({success:true,agent:{name:'KestrelField'},recentComments:[]});};await assert.rejects(publishReply(x.store,d.id,x.path,fake,x.now),/moderation_cooldown/);assert.deepEqual(await runSocialCycle(x.store,x.path,fake,x.now,async()=>{models++;return {text:'unused',provider:'ollama',model:'test'};}),{skipped:true});assert.equal(models,0);assert.equal(writes,0);assert.equal(x.store.db.prepare('SELECT attempted_at FROM social_replies').get()?.attempted_at,null);}finally{x.close();}});
test('profile and own post observations validate identity and continue when profile read fails',async()=>{const x=fixture();try{reply(x);x.store.db.prepare("INSERT INTO outreach_drafts(id,service_id,body,status) VALUES('intro','text-stats','Authored introduction','APPROVED')").run();x.store.db.prepare("INSERT INTO moltbook_publications(draft_id,content_hash,title,submolt,status,attempted_at,post_id) VALUES('intro','hash','Hello','agents','PUBLISHED',?,'intro-post')").run(x.now);const fake:any=async(url:string)=>{if(url.includes('/agents/profile'))return Response.json({success:true,agent:{name:'KestrelField'},recentComments:[{id:'comment-r',content:'Wrong content',post:{id:'p'},is_spam:true}]});return Response.json({post:{id:'intro-post',title:'Hello',content:'Authored introduction',author:{name:'KestrelField'},is_spam:true,verification_status:'verified'}});};await reconcileProfileAndPosts(x.store,x.path,fake,x.now);assert.equal(x.store.db.prepare("SELECT moderation FROM social_observations WHERE target='reply:r'").get()?.moderation,'MISMATCH');assert.equal(x.store.db.prepare("SELECT moderation FROM social_observations WHERE target='post:intro'").get()?.moderation,'SPAM');const failed:any=async(url:string)=>url.includes('/agents/profile')?new Response('',{status:503}):fake(url);assert.equal((await reconcileProfileAndPosts(x.store,x.path,failed,x.now+1800001)).failures,1);assert.equal(x.store.db.prepare("SELECT checked_at FROM social_observations WHERE target='post:intro'").get()?.checked_at,x.now+1800001);}finally{x.close();}});
test('numbered evidence resolves exact external source and rejects invented IDs and our own context',()=>{const source='Independent observers need an append-only state log. It costs storage and a separate read path.',excerpts=sourceExcerpts(source),d={action:'help',need:'Inspect state independently of dispatch.',reason:'Separate the observation failure channel.',evidence:1,body:'A concrete useful contribution.'};assert.equal(parseSocialDecision(JSON.stringify(d),source,false,excerpts).evidence,excerpts[0].text);assert.throws(()=>parseSocialDecision(JSON.stringify({...d,evidence:99}),source,false,excerpts),/decision_invalid_evidence/);assert.throws(()=>parseSocialDecision(JSON.stringify({...d,evidence:'My own earlier reply about verification.'}),source,false,excerpts),/decision_evidence_not_in_source/);});
test('prior contributions and repeated questions cannot be published as new answers',()=>{const x=fixture();try{const old='The minimal primitive is a timestamped expected versus observed state tuple at dispatch. This lets the system report divergence without depending on inference or side channels. Does the system support returning a versioned state with a known divergence point during read?';reply(x,'r',old);assert.equal(similarContribution(old,old),true);assert.throws(()=>validateContributionHistory(x.store,old),/reply_repeats_own_contribution/);assert.throws(()=>validateContributionHistory(x.store,'A separate checksum reader could catch corrupted entries at storage cost. Does the system support returning a versioned state with a known divergence point during read?'),/reply_repeats_previous_question/);assert.throws(()=>validateContributionHistory(x.store,'A suggestion for robust state storage. Ask: is this useful?'),/reply_template_residue/);assert.doesNotThrow(()=>validateContributionHistory(x.store,'An append-only checkpoint can include a checksum verified by a separate reader. It detects corrupted snapshots but adds storage and requires the reader to avoid the writer’s credentials.'));}finally{x.close();}});
test('profile sync verifies remote state, uses truthful payment status and is durable and idempotent',async()=>{const x=fixture();try{let description='Old profile',patches=0;const fake:any=async(_url:string,init:any)=>{if(init.method==='PATCH'){patches++;description=JSON.parse(init.body).description;return Response.json({success:true});}return Response.json({agent:{description}});};assert.equal((await syncSocialProfile(x.store,x.path,fake,x.now)).ok,true);assert.equal(description,expectedProfileDescription(x.store));assert.match(description,/payments are currently paused/);await syncSocialProfile(x.store,x.path,fake,x.now+1);await syncSocialProfile(x.store,x.path,fake,x.now+3600001);assert.equal(patches,1);assert.equal(x.store.db.prepare('SELECT confirmed_at FROM social_profile_sync').get()?.confirmed_at,x.now+3600001);const fail:any=async()=>Response.json({agent:{description:'Stale profile'}});assert.equal((await syncSocialProfile(x.store,x.path,fail,x.now+7200002)).error_code,'profile_sync_unconfirmed');assert.equal(x.store.db.prepare('SELECT confirmed_at FROM social_profile_sync').get()?.confirmed_at,x.now+3600001);}finally{x.close();}});
test('thread scans rotate through older conversations instead of starving them',async()=>{const x=fixture();try{for(let i=0;i<6;i++){x.store.db.prepare('INSERT INTO social_discussions(id,title,body,author,community,seen_at) VALUES(?,?,?,?,?,?)').run('p'+i,'Thread','Thread body','Alice','agents',x.now);x.store.db.prepare("INSERT INTO social_replies(id,post_id,body,status,comment_id,attempted_at) VALUES(?,?,?,'PUBLISHED',?,?)").run('r'+i,'p'+i,'Own reply','c'+i,x.now-i);}const read=new Set<string>();const fake:any=async(url:string)=>{read.add(url.split('/posts/')[1].split('/')[0]);return Response.json({comments:[]});};await scanFollowups(x.store,x.path,fake,x.now);assert.equal(read.size,5);await scanFollowups(x.store,x.path,fake,x.now+600001);assert.equal(read.size,6);}finally{x.close();}});

test('empty admin drafts can be archived but cannot be approved or sent',()=>{const x=fixture();try{const d=draftReply(x.store,'p');assert.equal(d.body,'');assert.throws(()=>reviewReply(x.store,d.id,'','APPROVED'),/Reply must/);reviewReply(x.store,d.id,'','ARCHIVED');assert.equal(x.store.db.prepare('SELECT status FROM social_replies').get()?.status,'ARCHIVED');}finally{x.close();}});
test('core evidence separates paid and test activity without claiming customer adoption',async()=>{const {coreEvidence}=await import('../src/agent-core.ts');const x=fixture();try{const agent=x.store.register('test-agent','Operator test');x.store.submit(agent.id,'text-stats',JSON.stringify({text:'Example'}),'first-job');const evidence=coreEvidence(x.store,'inspect_onboarding',x.now);assert.equal(evidence.paid_completed,0);assert.match(evidence.limitations,/operator tests/);assert.ok(Array.isArray(coreEvidence(x.store,'inspect_jobs',x.now).payment_mode_outcomes));}finally{x.close();}});

test('legacy restricted visibility migrates once without resetting balances or verification history',()=>{const x=fixture();try{reply(x);x.store.db.prepare("INSERT INTO social_visibility(reply_id,visibility,checked_at,verification_status) VALUES('r','VISIBLE_RESTRICTED',?,'verified')").run(x.now);const a=x.store.register('Legacy balance','Before migration');x.store.db.close();let restored=openStore(x.dir+'/data');assert.equal(restored.db.prepare('SELECT credits FROM agents WHERE id=?').get(a.id)?.credits,100);assert.equal(restored.db.prepare('SELECT status FROM social_replies').get()?.status,'PUBLISHED');assert.equal(moderationPolicy(restored,x.now).restricted_items,1);restored.db.close();restored=openStore(x.dir+'/data');assert.equal(restored.db.prepare('SELECT count(*) AS n FROM social_observation_history').get()?.n,1);restored.db.close();}finally{rmSync(x.dir,{recursive:true,force:true});}});

test('paraphrased Kai follow-up question is caught despite changed verb forms',()=>{const x=fixture();try{reply(x,'r','A concrete observation contract. Does the system allow a read operation to return a versioned state with a known divergence point, even if the final output is visible?');assert.throws(()=>validateContributionHistory(x.store,'A distinct proposed mechanism using independent checkpoints at storage cost. Does the system support returning a versioned state with a known divergence point during read?'),/reply_repeats_previous_question/);}finally{x.close();}});

test('promotion cooldown does not prohibit ordinary technical BNB discussion',()=>{const x=fixture();try{recordObservation(x.store,'post:intro','post_api',{is_spam:true},true,x.now);assert.doesNotThrow(()=>assertModerationAllowsWrite(x.store,'A BNB receipt needs confirmation and canonical block checks.',x.now+6*3600000));assert.throws(()=>assertModerationAllowsWrite(x.store,'I operate Literate Bassoon; try our text services.',x.now+6*3600000),/moderation_promotion_cooldown/);}finally{x.close();}});
