import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {openStore} from '../src/store.ts';
import {runSocialCycle,setAutonomy,autonomyStatus} from '../src/social-autonomy.ts';
import {flattenComments,scanFollowups} from '../src/social-threads.ts';
const postBody='Queue retries need durable request identifiers and reliable result records.';
const ownBody='Use durable request identifiers and result records for queue retries.';
const incomingBody='What about durable result records when a worker lease expires during queue retries?';
const reply='When a worker lease expires, durable result records should still be keyed by request identifiers. Queue retries should first reconcile the stored result and the receiver state before starting another execution. A lease limits concurrent workers but cannot prove the receiver did nothing. Is your receiver able to query the result by request identifier?';
function fixture(now=Date.now()){const dir=mkdtempSync(tmpdir()+'/threads-'),store=openStore(dir+'/data'),path=dir+'/identity.json';writeFileSync(path,JSON.stringify({name:'KestrelField',api_key:'test-secret'}));store.setOperator(true,'ollama','test',50);store.db.prepare('INSERT INTO social_discussions(id,title,body,author,community,seen_at,full_content,source_created_at) VALUES(?,?,?,?,?,?,1,?)').run('post','Queue retries',postBody,'OtherAgent','agentops',now,new Date(now-86400000).toISOString());store.db.prepare("INSERT INTO social_replies(id,post_id,body,status,attempted_at,comment_id) VALUES('root','post',?,'PUBLISHED',?,'our-comment')").run(ownBody,now-7200000);return {dir,store,path,close(){store.db.close();rmSync(dir,{recursive:true,force:true});}};}
function tree(now:number){return [{id:'our-comment',content:ownBody,author:{name:'KestrelField'},replies:[{id:'incoming',content:incomingBody,author:{name:'OtherAgent'},created_at:new Date(now-1000).toISOString()},{id:'self',content:incomingBody,author:{name:'KestrelField'},created_at:new Date(now-1000).toISOString()}]},{id:'unrelated',content:incomingBody,author:{name:'SomeoneElse'},created_at:new Date(now-1000).toISOString()}];}
test('thread scan selects direct responses to confirmed own comments, excluding self and unrelated comments',async()=>{const now=Date.now(),x=fixture(now);try{setAutonomy(x.store,true);let reads=0;const fake=async()=>{reads++;return new Response(JSON.stringify({comments:tree(now)}));};assert.equal((await scanFollowups(x.store,x.path,fake as typeof fetch,now)).found,1);assert.equal(x.store.db.prepare('SELECT id FROM social_incoming').get()?.id,'incoming');assert.deepEqual(await scanFollowups(x.store,x.path,fake as typeof fetch,now+1),{skipped:true});assert.equal(reads,2);assert.equal(flattenComments(tree(now)).find(c=>c.id==='incoming').parent_id,'our-comment');}finally{x.close();}});
test('follow-up uses parent_id, preserved context, shared budget and never replies twice to the same incoming comment',async()=>{const now=Date.now(),x=fixture(now);try{setAutonomy(x.store,true);let writes=0,models=0;const fake=async(url:any,init:any)=>{if(String(url).includes('/comments?'))return new Response(JSON.stringify({comments:tree(now)}));if(String(url).endsWith('/agents/status'))return new Response(JSON.stringify({status:'claimed'}));if(String(url).endsWith('/comments')){writes++;assert.equal(JSON.parse(init.body).parent_id,'incoming');return new Response(JSON.stringify({comment:{id:'our-followup'}}));}return new Response(JSON.stringify({post:{id:'post',title:'Queue retries',content:postBody,author:{name:'OtherAgent'}}}));};const gen=async(_cfg:any,task:string,source:string)=>{models++;assert.equal(task,'social-decision');assert.ok(source.includes(incomingBody));assert.ok(source.includes(ownBody));return {text:decision(reply),provider:'ollama',model:'test'};};assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen)).status,'PUBLISHED');assert.equal(x.store.db.prepare("SELECT parent_id FROM social_replies WHERE id!='root'").get()?.parent_id,'incoming');assert.equal(x.store.db.prepare('SELECT count(*) AS n FROM social_replies').get()?.n,2);await runSocialCycle(x.store,x.path,fake as typeof fetch,now+3600001,gen);assert.equal(models,1);assert.equal(writes,1);assert.equal(autonomyStatus(x.store).last_reason,'no_fresh_unanswered_source');}finally{x.close();}});
test('thread responses altered between scan and dispatch never reach model or publishing',async()=>{const now=Date.now(),x=fixture(now);try{setAutonomy(x.store,true);let reads=0,models=0;const fake=async(url:any)=>{if(String(url).includes('/comments?')){reads++;const comments=tree(now);if(reads>1)comments[0].replies![0].content='Changed content';return new Response(JSON.stringify({comments}));}return new Response(JSON.stringify({post:{id:'post',title:'Queue retries',content:postBody,author:{name:'OtherAgent'}}}));};const gen=async()=>{models++;return {text:decision(reply),provider:'ollama',model:'test'};};assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen)).error_code,'source_changed');assert.equal(models,0);}finally{x.close();}});
test('cycle diagnostics distinguish paused, cooldown, blocked delivery and missing sources',async()=>{const now=Date.now(),x=fixture(now);try{const fake=async()=>new Response(JSON.stringify({comments:[]}));await runSocialCycle(x.store,x.path,fake as typeof fetch,now);assert.equal(autonomyStatus(x.store).last_reason,'autonomy_paused');setAutonomy(x.store,true);x.store.db.prepare("UPDATE social_replies SET status='UNCERTAIN' WHERE id='root'").run();await runSocialCycle(x.store,x.path,fake as typeof fetch,now+1);assert.equal(autonomyStatus(x.store).last_reason,'blocked_UNCERTAIN');x.store.db.prepare("UPDATE social_replies SET status='PUBLISHED' WHERE id='root'").run();x.store.db.prepare('UPDATE social_autonomy SET checked_at=? WHERE id=1').run(now);await runSocialCycle(x.store,x.path,fake as typeof fetch,now+2);assert.equal(autonomyStatus(x.store).last_reason,'hourly_cooldown');assert.equal(autonomyStatus(x.store).next_cycle_at,now+3600000);}finally{x.close();}});
test('legacy single-reply schema migrates without losing publication or pending verification records',()=>{const now=Date.now(),x=fixture(now);try{x.store.db.exec(`DROP INDEX social_reply_content; DROP INDEX social_reply_root; DROP INDEX social_reply_parent; ALTER TABLE social_replies RENAME TO migrated_replies; CREATE TABLE social_replies(id TEXT PRIMARY KEY,post_id TEXT UNIQUE NOT NULL REFERENCES social_discussions(id),body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'DRAFT',created_at TEXT DEFAULT CURRENT_TIMESTAMP,attempted_at INTEGER,content_hash TEXT,comment_id TEXT,challenge TEXT,verification_code TEXT,expires_at TEXT,error_code TEXT); INSERT INTO social_replies SELECT id,post_id,body,status,created_at,attempted_at,content_hash,comment_id,challenge,verification_code,expires_at,error_code FROM migrated_replies; DROP TABLE migrated_replies;`);x.store.db.prepare("UPDATE social_replies SET status='PENDING_VERIFICATION',challenge='test challenge',verification_code='test-code',expires_at=? WHERE id='root'").run(new Date(now+60000).toISOString());x.store.db.close();const restored=openStore(x.dir+'/data');try{const row=restored.db.prepare("SELECT * FROM social_replies WHERE id='root'").get()!;assert.equal(row.body,ownBody);assert.equal(row.status,'PENDING_VERIFICATION');assert.equal(row.comment_id,'our-comment');assert.equal(row.verification_code,'test-code');assert.equal(row.parent_id,null);restored.db.prepare("INSERT INTO social_replies(id,post_id,body,parent_id) VALUES('followup','post',?,'incoming')").run(reply);assert.throws(()=>restored.db.prepare("INSERT INTO social_replies(id,post_id,body,parent_id) VALUES('duplicate','post',?,'incoming')").run(reply),/UNIQUE/);assert.throws(()=>restored.db.prepare("INSERT INTO social_replies(id,post_id,body) VALUES('duplicate-root','post',?)").run(reply),/UNIQUE/);}finally{restored.db.close();}}finally{rmSync(x.dir,{recursive:true,force:true});}});
test('rejected follow-up stays unanswered, retries once with feedback and never repeats a write',async()=>{
 const now=Date.now(),x=fixture(now);try{
 setAutonomy(x.store,true);let models=0,writes=0;
 const fake=async(url:any)=>{if(String(url).includes('/comments?'))return new Response(JSON.stringify({comments:tree(now)}));if(String(url).endsWith('/agents/status'))return new Response(JSON.stringify({status:'claimed'}));if(String(url).endsWith('/comments')){writes++;return new Response(JSON.stringify({comment:{id:'followup'}}));}return new Response(JSON.stringify({post:{id:'post',title:'Queue retries',content:postBody,author:{name:'OtherAgent'}}}));};
 const gen=async(_cfg:any,_task:string,source:string)=>{models++;if(models===1)return {text:decision(reply+' Why? Another question?'),provider:'ollama',model:'test'};assert.ok(source.includes('reply_too_many_questions'));return {text:decision(reply),provider:'ollama',model:'test'};};
 assert.equal((await runSocialCycle(x.store,x.path,fake as typeof fetch,now,gen)).error_code,'reply_too_many_questions');assert.equal(autonomyStatus(x.store,now).incoming_waiting,1);assert.equal(writes,0);
 await runSocialCycle(x.store,x.path,fake as typeof fetch,now+1,gen);assert.equal(models,1);
 const retried=await runSocialCycle(x.store,x.path,fake as typeof fetch,now+3600001,gen);assert.equal(retried.status,'PUBLISHED',JSON.stringify(retried));assert.equal(autonomyStatus(x.store,now+3600001).incoming_waiting,0);
 await runSocialCycle(x.store,x.path,fake as typeof fetch,now+7200002,gen);assert.equal(models,2);assert.equal(writes,1);
 }finally{x.close();}
});
test('two rejected drafts exhaust regeneration while the incoming message remains open',async()=>{
 const now=Date.now(),x=fixture(now);try{setAutonomy(x.store,true);let calls=0;
 const fake=async(url:any)=>String(url).includes('/comments?')?new Response(JSON.stringify({comments:tree(now)})):new Response(JSON.stringify({post:{id:'post',title:'Queue retries',content:postBody,author:{name:'OtherAgent'}}}));
 const gen=async()=>{calls++;return {text:decision(reply+' Why? Again?'),provider:'ollama',model:'test'};};
 for(let i=0;i<3;i++)await runSocialCycle(x.store,x.path,fake as typeof fetch,now+i*3600001,gen);
 assert.equal(calls,2);assert.equal(autonomyStatus(x.store,now+7200002).incoming_waiting,1);assert.equal(x.store.db.prepare('SELECT count(*) AS n FROM social_generation WHERE parent_id=?').get('incoming')?.n,2);
 }finally{x.close();}
});

function decision(replyText:string){return JSON.stringify({action:"help",need:"Understand reliable queue retries and durable results.",evidence:1,reason:"Offer a concrete mechanism addressing the source constraint.",body:replyText});}
