import {randomUUID} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
export const USDT='0x55d398326f99059ff775485246999027b3197955';
const transfer='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
export type Asset='USDT'|'BNB';
export function asset(v:unknown):Asset {if(v!=='USDT'&&v!=='BNB')throw Error('Asset must be USDT or BNB');return v;}
export function units(v:unknown):bigint {if(typeof v!=='string'||!/^(0|[1-9][0-9]{0,59})$/.test(v))throw Error('Amount must be an unsigned atomic-unit string');return BigInt(v);}
export function address(v:unknown):string {if(typeof v!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(v)||/^0x0{40}$/i.test(v))throw Error('Invalid BNB Chain address');return v.toLowerCase();}
function txhash(v:unknown):string{if(typeof v!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(v))throw Error('Invalid transaction hash');return v.toLowerCase();}
export function initMoney(db:DatabaseSync){db.exec(`
 CREATE TABLE IF NOT EXISTS money_settings(id INTEGER PRIMARY KEY CHECK(id=1),enabled INTEGER NOT NULL DEFAULT 0);INSERT OR IGNORE INTO money_settings(id) VALUES(1);
 CREATE TABLE IF NOT EXISTS money_addresses(address TEXT PRIMARY KEY,agent_id TEXT UNIQUE REFERENCES agents(id),assigned_ms INTEGER);
 CREATE TABLE IF NOT EXISTS money_treasury(address TEXT PRIMARY KEY);
 CREATE TABLE IF NOT EXISTS money_balances(owner TEXT NOT NULL,asset TEXT NOT NULL,amount TEXT NOT NULL DEFAULT '0',PRIMARY KEY(owner,asset));
 CREATE TABLE IF NOT EXISTS money_ledger(id INTEGER PRIMARY KEY,owner TEXT NOT NULL,asset TEXT NOT NULL,amount TEXT NOT NULL,kind TEXT NOT NULL,reference TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS money_prices(service_id TEXT NOT NULL REFERENCES services(id),asset TEXT NOT NULL,amount TEXT NOT NULL,PRIMARY KEY(service_id,asset));
 CREATE TABLE IF NOT EXISTS money_events(tx_hash TEXT NOT NULL,event_index INTEGER NOT NULL,asset TEXT NOT NULL,amount TEXT NOT NULL,address TEXT NOT NULL,block_hash TEXT NOT NULL,reference TEXT NOT NULL,PRIMARY KEY(tx_hash,event_index));
 CREATE TABLE IF NOT EXISTS money_withdrawals(id TEXT PRIMARY KEY,agent_id TEXT NOT NULL,asset TEXT NOT NULL,amount TEXT NOT NULL,address TEXT NOT NULL,status TEXT NOT NULL,idempotency_key TEXT NOT NULL,tx_hash TEXT UNIQUE,event_index INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(agent_id,idempotency_key));`);
 for(const [name,def] of [['money_asset','TEXT'],['money_amount','TEXT'],['money_fee','TEXT']])if(!db.prepare('PRAGMA table_info(jobs)').all().some(c=>c.name===name))db.exec(`ALTER TABLE jobs ADD COLUMN ${name} ${def}`);
}
export function balance(db:DatabaseSync,owner:string,a:Asset){return BigInt(String(db.prepare('SELECT amount FROM money_balances WHERE owner=? AND asset=?').get(owner,a)?.amount||'0'));}
export function move(db:DatabaseSync,owner:string,a:Asset,delta:bigint,kind:string,ref:string){const next=balance(db,owner,a)+delta;if(next<0n)throw Error('Insufficient '+a+' balance');if(next>=10n**60n)throw Error('Balance limit exceeded');db.prepare('INSERT INTO money_balances(owner,asset,amount) VALUES(?,?,?) ON CONFLICT(owner,asset) DO UPDATE SET amount=excluded.amount').run(owner,a,next.toString());db.prepare('INSERT INTO money_ledger(owner,asset,amount,kind,reference) VALUES(?,?,?,?,?)').run(owner,a,delta.toString(),kind,ref);}
export function reserveMoney(db:DatabaseSync,buyer:string,service:string,a:Asset,job:string){const p=db.prepare('SELECT amount FROM money_prices WHERE service_id=? AND asset=?').get(service,a);if(!p)throw Error('Service has no '+a+' price');const n=units(p.amount);if(n===0n)throw Error('Paid price must be positive');move(db,buyer,a,-n,'job_reserved',job);move(db,'escrow',a,n,'job_reserved',job);return {amount:n.toString(),fee:(n/10n).toString()};}
export function settleMoney(db:DatabaseSync,j:any,status:string){const a=asset(j.money_asset),n=units(j.money_amount),fee=units(j.money_fee);move(db,'escrow',a,-n,'job_settled',j.id);if(status==='COMPLETED'){if(j.provider_id){move(db,String(j.provider_id),a,n-fee,'job_earned',j.id);move(db,'platform',a,fee,'platform_fee',j.id);}else move(db,'platform',a,n,'platform_service',j.id);}else move(db,String(j.buyer_id),a,n,'job_refund',j.id);}
export function moneyConfig(env=process.env){const urls=[env.BSC_RPC_URL,env.BSC_RPC_SECONDARY_URL].filter(Boolean) as string[];for(const raw of urls){const u=new URL(raw);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error('BSC RPC must use HTTPS or loopback HTTP');}return {allow:env.PAYMENTS_ALLOW_LIVE==='1',urls,confirmations:20};}
export function openPayments(store:any,env=process.env,fetcher=fetch){const db:DatabaseSync=store.db;const cfg=moneyConfig(env);
 const treasury=(env.BSC_TREASURY_ADDRESSES||'').split(',').filter(Boolean).map(v=>address(v.trim()));
 const addresses=(env.BSC_DEPOSIT_ADDRESSES||'').split(',').filter(Boolean).map(v=>address(v.trim()));
 store.transaction(()=>{for(const a of treasury)db.prepare('INSERT OR IGNORE INTO money_treasury(address) VALUES(?)').run(a);for(const a of addresses)db.prepare('INSERT OR IGNORE INTO money_addresses(address) VALUES(?)').run(a);});
 let rpcId=0,changingSettings=false;
 async function rpc(url:string,method:string,params:any[]){const id=++rpcId;try{const r=await fetcher(url,{method:'POST',redirect:'error',signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id,method,params})});if(!r.ok)throw Error();const text=await r.text();if(text.length>2000000)throw Error();const b=JSON.parse(text);if(b.id!==id||b.error||!('result'in b))throw Error();return b.result;}catch{throw Error('Payment RPC unavailable');}}
 async function checkRPC(url:string){if(await rpc(url,'eth_chainId',[])!=='0x38')throw Error('Payment RPC is not BNB Chain mainnet');const decimals=await rpc(url,'eth_call',[{to:USDT,data:'0x313ce567'},'latest']);if(typeof decimals!=='string'||!/^0x[0-9a-fA-F]{1,64}$/.test(decimals)||BigInt(decimals)!==18n)throw Error('USDT contract decimals mismatch');}
 function overview(){return {enabled:Boolean(db.prepare('SELECT enabled FROM money_settings WHERE id=1').get()?.enabled)&&cfg.allow,armed:cfg.allow,rpc_configured:cfg.urls.length===2&&cfg.urls[0]!==cfg.urls[1],network:'BNB Smart Chain',chain_id:56,assets:['USDT','BNB'],decimals:18,usdt_contract:USDT,confirmations:cfg.confirmations,free_addresses:Number(db.prepare('SELECT count(*) AS n FROM money_addresses WHERE agent_id IS NULL').get()?.n),withdrawals:db.prepare('SELECT * FROM money_withdrawals ORDER BY rowid DESC LIMIT 100').all(),platform_balances:['USDT','BNB'].map(a=>({asset:a,amount:balance(db,'platform',a as Asset).toString()}))};}
 function enabled(){if(!overview().enabled)throw Error('Real payments are paused');}
 async function readiness(){if(!cfg.allow)throw Error('Set PAYMENTS_ALLOW_LIVE=1 in the private server environment first');if(cfg.urls.length!==2||cfg.urls[0]===cfg.urls[1])throw Error('Configure two independent BSC RPC endpoints');if(!db.prepare('SELECT address FROM money_treasury LIMIT 1').get())throw Error('Configure controlled treasury/gas-funding addresses first');if(!db.prepare('SELECT address FROM money_addresses LIMIT 1').get())throw Error('Configure controlled deposit addresses first');await Promise.all(cfg.urls.map(checkRPC));return {ok:true,chain_id:56,usdt_decimals:18};}
 async function setEnabled(value:boolean){if(typeof value!=='boolean')throw Error('enabled must be boolean');if(changingSettings)throw Error('Payment settings update in progress');changingSettings=true;try{if(value)await readiness();store.transaction(()=>{db.prepare('UPDATE money_settings SET enabled=? WHERE id=1').run(value?1:0);store.audit(value?'payments_enabled':'payments_paused','BNB Chain');});return overview();}finally{changingSettings=false;}}
 function wallet(owner:string){return {network:'BNB Smart Chain',chain_id:56,enabled:overview().enabled,decimals:18,usdt_contract:USDT,deposit_address:db.prepare('SELECT address FROM money_addresses WHERE agent_id=?').get(owner)?.address||null,balances:['USDT','BNB'].map(a=>({asset:a,amount:balance(db,owner,a as Asset).toString()})),ledger:db.prepare('SELECT asset,amount,kind,reference,created_at FROM money_ledger WHERE owner=? ORDER BY id DESC LIMIT 100').all(owner),withdrawals:db.prepare('SELECT * FROM money_withdrawals WHERE agent_id=? ORDER BY rowid DESC LIMIT 100').all(owner)};}
 function depositAddress(owner:string){enabled();return store.transaction(()=>{const old=db.prepare('SELECT address FROM money_addresses WHERE agent_id=?').get(owner);if(old)return old;const free=db.prepare('SELECT address FROM money_addresses WHERE agent_id IS NULL LIMIT 1').get();if(!free)throw Error('No deposit addresses available; contact the operator');db.prepare('UPDATE money_addresses SET agent_id=?,assigned_ms=? WHERE address=?').run(owner,Date.now(),free.address);return {address:free.address};});}
 async function proof(a:Asset,hash:string,index:number,to:string){if(cfg.urls.length!==2||cfg.urls[0]===cfg.urls[1])throw Error('Configure two independent BSC RPC endpoints');const proofs=await Promise.all(cfg.urls.map(async url=>{await checkRPC(url);const receipt=await rpc(url,'eth_getTransactionReceipt',[hash]);if(!receipt||receipt.status!=='0x1'||receipt.transactionHash?.toLowerCase()!==hash)throw Error('Transaction pending or unsuccessful');const [head,block,finalized]=await Promise.all([rpc(url,'eth_blockNumber',[]),rpc(url,'eth_getBlockByNumber',[receipt.blockNumber,false]),rpc(url,'eth_getBlockByNumber',['finalized',false])]);if(block?.hash?.toLowerCase()!==receipt.blockHash?.toLowerCase())throw Error('Transaction is not on the canonical chain');if(!finalized||BigInt(finalized.number)<BigInt(receipt.blockNumber)||BigInt(head)-BigInt(receipt.blockNumber)+1n<BigInt(cfg.confirmations))throw Error('Transaction needs more confirmations');let n:bigint,from:string;
 if(a==='USDT'){const log=receipt.logs?.find((l:any)=>Number(BigInt(l.logIndex))===index);if(!log||log.removed||log.address?.toLowerCase()!==USDT||log.topics?.length!==3||log.topics[0]?.toLowerCase()!==transfer||log.topics[2]?.toLowerCase()!=='0x'+'0'.repeat(24)+to.slice(2)||!/^0x[0-9a-fA-F]{64}$/.test(log.data))throw Error('No matching USDT transfer');n=BigInt(log.data);from=address('0x'+String(log.topics[1]).slice(-40));}else{if(index!==-1)throw Error('BNB event index must be -1');const tx=await rpc(url,'eth_getTransactionByHash',[hash]);if(tx?.hash?.toLowerCase()!==hash||tx?.to?.toLowerCase()!==to||tx?.blockHash?.toLowerCase()!==receipt.blockHash?.toLowerCase()||!['0x','0x0'].includes(tx.input))throw Error('No matching plain BNB transfer');n=BigInt(tx.value);from=address(tx.from);}
 if(n<=0n||n>=10n**60n)throw Error('Invalid transfer amount');return {amount:n.toString(),from,block_hash:String(receipt.blockHash).toLowerCase(),block_time:Number(BigInt(block.timestamp))*1000};}));if(JSON.stringify(proofs[0])!==JSON.stringify(proofs[1]))throw Error('BSC RPC providers disagree');return proofs[0];}
 function event(hash:string,index:number,a:Asset,p:any,to:string,ref:string){db.prepare('INSERT INTO money_events(tx_hash,event_index,asset,amount,address,block_hash,reference) VALUES(?,?,?,?,?,?,?)').run(hash,index,a,p.amount,to,p.block_hash,ref);}
 async function deposit(owner:string,b:any){const a=asset(b.asset),h=txhash(b.tx_hash),i=a==='BNB'?-1:b.event_index;if(!Number.isSafeInteger(i)||i< -1||i>100000)throw Error('Invalid event_index');const dest=db.prepare('SELECT address,assigned_ms FROM money_addresses WHERE agent_id=?').get(owner);if(!dest)throw Error('Request a deposit address first');const existing=db.prepare('SELECT * FROM money_events WHERE tx_hash=? AND event_index=?').get(h,i);if(existing){if(existing.reference!=='deposit:'+owner||existing.asset!==a)throw Error('Transfer already used');return {credited:true,amount:existing.amount,asset:a,reused:true};}const p=await proof(a,h,i,String(dest.address));if(db.prepare('SELECT address FROM money_treasury WHERE address=?').get(p.from)||db.prepare('SELECT address FROM money_addresses WHERE address=?').get(p.from))throw Error('Internal wallet transfers cannot credit deposits');if(p.block_time<Number(dest.assigned_ms)-2000)throw Error('Transfer predates address assignment');return store.transaction(()=>{const old=db.prepare('SELECT * FROM money_events WHERE tx_hash=? AND event_index=?').get(h,i);if(old){if(old.reference!=='deposit:'+owner||old.asset!==a)throw Error('Transfer already used');return {credited:true,amount:old.amount,asset:a,reused:true};}event(h,i,a,p,String(dest.address),'deposit:'+owner);move(db,owner,a,units(p.amount),'deposit',h+':'+i);return {credited:true,amount:p.amount,asset:a};});}
 function price(service:string,a:Asset,amount:string){const n=units(amount);if(n===0n)throw Error('Paid price must be positive');db.prepare('INSERT INTO money_prices(service_id,asset,amount) VALUES(?,?,?) ON CONFLICT(service_id,asset) DO UPDATE SET amount=excluded.amount').run(service,a,n.toString());}
 function withdraw(owner:string,b:any,key:string){enabled();const a=asset(b.asset),n=units(b.amount),to=address(b.address);if(n<=0n)throw Error('Withdrawal amount must be positive');if(db.prepare('SELECT address FROM money_addresses WHERE address=?').get(to))throw Error('Withdraw to an external address');return store.transaction(()=>{const old=db.prepare('SELECT * FROM money_withdrawals WHERE agent_id=? AND idempotency_key=?').get(owner,key);if(old){if(old.asset!==a||old.amount!==n.toString()||old.address!==to)throw Error('Idempotency key already used for a different withdrawal');return old;}const id=randomUUID();move(db,owner,a,-n,'withdrawal_reserved',id);move(db,'withdrawal_escrow',a,n,'withdrawal_reserved',id);db.prepare("INSERT INTO money_withdrawals(id,agent_id,asset,amount,address,status,idempotency_key) VALUES(?,?,?,?,?,'REQUESTED',?)").run(id,owner,a,n.toString(),to,key);return db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);});}
 function cancelWithdrawal(id:string,owner?:string){return store.transaction(()=>{const w=db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);if(!w||owner&&w.agent_id!==owner)throw Error('Withdrawal not found');if(w.status!=='REQUESTED')throw Error('Withdrawal already locked or settled');db.prepare("UPDATE money_withdrawals SET status='CANCELLED' WHERE id=?").run(id);move(db,'withdrawal_escrow',asset(w.asset),-units(w.amount),'withdrawal_cancelled',id);move(db,String(w.agent_id),asset(w.asset),units(w.amount),'withdrawal_refund',id);return {ok:true};});}
 function lockWithdrawal(id:string){enabled();return store.transaction(()=>{const change=db.prepare("UPDATE money_withdrawals SET status='PAYING' WHERE id=? AND status='REQUESTED'").run(id);if(!change.changes)throw Error('Withdrawal not available for payout');store.audit('withdrawal_locked',id);return db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);});}
 function attachPayout(id:string,b:any){const h=txhash(b.tx_hash);return store.transaction(()=>{const w=db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);if(!w||!['PAYING','BROADCAST'].includes(String(w.status)))throw Error('Lock withdrawal before paying');if(w.tx_hash){if(w.tx_hash!==h)throw Error('Payout hash already recorded');return w;}const i=w.asset==='BNB'?-1:b.event_index;if(!Number.isSafeInteger(i)||i<0&&w.asset!=='BNB'||i>100000)throw Error('Invalid payout event_index');db.prepare("UPDATE money_withdrawals SET status='BROADCAST',tx_hash=?,event_index=? WHERE id=?").run(h,i,id);store.audit('withdrawal_broadcast',id);return db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);});}
 async function confirmPayout(id:string){const w=db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);if(!w)throw Error('Withdrawal not found');if(w.status==='PAID')return w;if(w.status!=='BROADCAST')throw Error('Record payout hash first');const a=asset(w.asset),p=await proof(a,String(w.tx_hash),Number(w.event_index),String(w.address));if(p.amount!==w.amount)throw Error('Payout amount mismatch');if(p.block_time<Date.parse(String(w.created_at)+'Z')-2000)throw Error('Payout predates withdrawal');return store.transaction(()=>{const changed=db.prepare("UPDATE money_withdrawals SET status='PAID' WHERE id=? AND status='BROADCAST'").run(id);if(!changed.changes)return db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);event(String(w.tx_hash),Number(w.event_index),a,p,String(w.address),'withdrawal:'+id);move(db,'withdrawal_escrow',a,-units(w.amount),'withdrawal_paid',id);store.audit('withdrawal_paid',id);return db.prepare('SELECT * FROM money_withdrawals WHERE id=?').get(id);});}
 return {overview,enabled,readiness,setEnabled,wallet,depositAddress,deposit,price,withdraw,cancelWithdrawal,lockWithdrawal,attachPayout,confirmPayout};
}
